In [4]:
import numpy as np

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
print(x)

[[1 2 3]
 [4 5 6]]


In [16]:
x.shape

(2, 3)

In [17]:
from scipy import sparse

In [23]:
# Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)
print("NumPy array: \n{}".format(eye))

NumPy array: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
